# netlify.toml  (replace the whole file)

[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "zod"]

# CORS for your Netlify Functions (keep if you were using these)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "${SITE_ORIGIN}"
    Access-Control-Allow-Methods = "GET, POST, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Credentials = "true"
