name: Netlify PR Preview

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    name: Deploy Preview to Netlify
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout PR branch
        uses: actions/checkout@v3

      - name: 🧰 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🛠 Build project
        run: npm run build

      - name: 🚀 Deploy to Netlify Preview
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy preview for PR #${{ github.event.pull_request.number }}"
          enable-commit-comment: true
          enable-pull-request-comment: true
          alias: deploy-preview-${{ github.event.pull_request.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
